
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

# https://github.com/babel/babel-eslint
parser: esprima

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  no-unused-expressions: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
