name: ESlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_linter_testing:
    name: Prepare Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.1.0
    
