on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: apps # only if a different glob is needed, default: src
