name: ESlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_linter_testing:
    runs-on: ubuntu-latest

    steps:
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1
