name: Prace.js
on:
  pull_request:
    types: [
      'opened',
      'edited',
      'reopened',
      'synchronize',
      'review_requested',
      'review_request_removed',
      'assigned',
      'unassigned',
      'labeled',
      'unlabeled',
      ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: innerspacetrainings/Prace.js@v1.0.0
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
